from enum import Enum
from pydantic import BaseModel, Field

from app.models.herb import HerbRecommendation


class TCMSyndrome(str, Enum):
    """
    Core TCM syndrome patterns this system can identify.
    This list can be expanded as the knowledge base grows.
    """
    QI_DEFICIENCY = "qi_deficiency"
    BLOOD_DEFICIENCY = "blood_deficiency"
    YIN_DEFICIENCY = "yin_deficiency"
    YANG_DEFICIENCY = "yang_deficiency"
    DAMPNESS = "dampness"
    HEAT_DAMP_HEAT = "heat_damp_heat"
    COLD = "cold"
    QI_STAGNATION = "qi_stagnation"
    BLOOD_STASIS = "blood_stasis"
    SPLEEN_QI_DEFICIENCY = "spleen_qi_deficiency"


class TongueObservation(BaseModel):
    """
    Structured description of tongue features, either provided
    directly by the user or generated by a vision-capable LLM
    from an uploaded image.
    """
    color: str = Field(..., description="e.g. pale, red, purple, dark red")
    coating: str = Field(..., description="e.g. thin white, thick yellow, none")
    shape: str = Field(..., description="e.g. swollen, thin, cracked, tooth-marked")
    moisture: str = Field(..., description="e.g. dry, normal, excessively wet")
    notes: str | None = Field(default=None, description="Any additional observations")


class SyndromeClassification(BaseModel):
    """
    Structured output of the syndrome-mapping step.
    This is the contract between the LLM reasoning step
    and the downstream herb retrieval step.
    """
    primary_pattern: TCMSyndrome
    secondary_patterns: list[TCMSyndrome] = Field(default_factory=list)
    confidence: float = Field(..., ge=0.0, le=1.0)
    reasoning: str = Field(..., description="Brief explanation of why this pattern was identified")
    affected_organs: list[str] = Field(default_factory=list)


class DiagnosisRequest(BaseModel):
    """
    Input to the /diagnose endpoint.
    """
    symptoms: str = Field(..., description="Free-text description of symptoms")
    tongue_observation: TongueObservation | None = Field(
        default=None,
        description="Optional structured tongue description"
    )


class DiagnosisResponse(BaseModel):
    """
    Full response from the /diagnose endpoint, including TCM + Caribbean
    herb recommendations retrieved from the Qdrant knowledge base based
    on the identified syndrome pattern(s).
    """
    classification: SyndromeClassification
    herb_recommendations: list[HerbRecommendation] = Field(
        default_factory=list,
        description="Herbs (TCM and/or Caribbean) relevant to the identified syndrome pattern"
    )
    disclaimer: str = (
        "This information is for educational purposes only and is based on "
        "traditional wellness frameworks. It is not a medical diagnosis and "
        "does not replace consultation with a licensed healthcare provider."
    )
